/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as InfantilRouteImport } from './routes/infantil'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contato' | '/feminino' | '/infantil' | '/novidades' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/feminino' | '/infantil' | '/novidades' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/feminino'
    | '/infantil'
    | '/novidades'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  FemininoRoute: typeof FemininoRoute
  InfantilRoute: typeof InfantilRoute
  NovidadesRoute: typeof NovidadesRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  FemininoRoute: FemininoRoute,
  InfantilRoute: InfantilRoute,
  NovidadesRoute: NovidadesRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
