/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as InfantilRouteImport } from './routes/infantil'
import { Route as NovidadesRouteImport } from './routes/novidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/novidades': typeof NovidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feminino' | '/infantil' | '/novidades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feminino' | '/infantil' | '/novidades'
  id: '__root__' | '/' | '/feminino' | '/infantil' | '/novidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FemininoRoute: typeof FemininoRoute
  InfantilRoute: typeof InfantilRoute
  NovidadesRoute: typeof NovidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FemininoRoute: FemininoRoute,
  InfantilRoute: InfantilRoute,
  NovidadesRoute: NovidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
